try:
	raise Exception()
except Exception as e:
	print("hello", str(e))
